services:
  hollo:
    image: ghcr.io/fedify-dev/hollo:canary
    ports:
      - "8888:8888"
    environment:
      DATABASE_URL: "postgres://freesky:freesky@postgres:5432/freesky"
      SECRET_KEY: "${SECRET_KEY}"
      LOG_LEVEL: "${LOG_LEVEL}"
      BEHIND_PROXY: "${BEHIND_PROXY}"
      DRIVE_DISK: s3
      STORAGE_URL_BASE: http://localhost:9000/hollo/
      S3_REGION: us-east-1
      S3_BUCKET: hollo
      S3_ENDPOINT_URL: http://minio:9000
      S3_FORCE_PATH_STYLE: "true"
      AWS_ACCESS_KEY_ID: minioadmin
      AWS_SECRET_ACCESS_KEY: minioadmin
    depends_on:
      - postgres
      - minio
      - create-bucket
    restart: no

  postgres:
    image: postgres:17
    environment:
      POSTGRES_USER: freesky
      POSTGRES_PASSWORD: freesky
      POSTGRES_DB: freesky
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: no

  minio:
    image: minio/minio:latest
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    volumes:
      - minio_data:/data
    command: ["server", "/data", "--console-address", ":9001"]

  create-bucket:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: |
      /bin/sh -c "
        /usr/bin/mc alias set minio http://minio:9000 minioadmin minioadmin;
        /usr/bin/mc mb minio/hollo;
        /usr/bin/mc anonymous set public minio/hollo;
        exit 0;
      "

volumes:
  postgres_data:
  minio_data:
